name: Reusable pmndrs/docs workflow

on:
  workflow_call:
    inputs:
      mdx:
        required: true
        type: string
      libname:
        required: true
        type: string

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - id: configurepages
        uses: actions/configure-pages@v5
      - run: |
          set -ex

          docker run --rm --init \
            -v "$MDX":/app/docs \
            -e BASE_PATH \
            -e DIST_DIR="$MDX/out$BASE_PATH" \
            -e MDX \
            -e NEXT_PUBLIC_LIBNAME \
            ghcr.io/pmndrs/docs:app-router npm run build
        env:
          BASE_PATH: ${{ steps.configurepages.outputs.base_path }}
          MDX: ${{ inputs.mdx }}
          NEXT_PUBLIC_LIBNAME: ${{ inputs.libname }}

      - run: ls -al ${{ inputs.mdx }}

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ inputs.mdx }}/out${{ steps.configurepages.outputs.base_path }}
