name: Reusable pmndrs/docs workflow

on:
  workflow_call:
    inputs:
      mdx:
        required: true
        type: string
      libname:
        required: true
        type: string
      inline_images_origin:
        required: false
        type: string
        default: 'https://github.com/${{ github.repository }}/raw/${{ github.ref_name }}'
      home_redirect:
        required: true
        type: string
        default: '/getting-started/introduction'

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - id: configurepages
        uses: actions/configure-pages@v5
      - run: |
          set -ex

          docker run --rm --init \
            -v "$MDX":/app/docs \
            -e BASE_PATH \
            -e DIST_DIR="$MDX/out$BASE_PATH" \
            -e MDX \
            -e NEXT_PUBLIC_LIBNAME \
            -e OUTPUT=export \
            -e HOME_REDIRECT \
            -e INLINE_IMAGES_ORIGIN \
            ghcr.io/pmndrs/docs:app-router npm run build
        env:
          BASE_PATH: ${{ steps.configurepages.outputs.base_path }}
          MDX: ${{ inputs.mdx }}
          NEXT_PUBLIC_LIBNAME: ${{ inputs.libname }}
          HOME_REDIRECT: ${{ inputs.home_redirect }}
          INLINE_IMAGES_ORIGIN: ${{ inputs.inline_images_origin }}

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ inputs.mdx }}/out${{ steps.configurepages.outputs.base_path }}
