name: Create and publish a multi-arch Docker image
on:
  push:
    branches: ['main', 'app-router']

jobs:
  build:
    uses: pmndrs/docs/.github/workflows/build.yml@app-router
    with:
      mdx: ./docs
      libname: 'pmndrs'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
